language: node_js
node_js:
  - 12

sudo: required
services:
  - docker

before_install:
  - docker build -t benoitdeclerck/frontend-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true benoitdeclerck/frontend-docker npm run test